### ISSUE TITLE
(Potentially) Faulty test cases?

### ISSUE THREAD

**Issue by iamgroot42** [cleverhans-lab/cleverhans#1161]
***The issue tracker should only be used to report bugs or feature requests. If you are looking for support from other library users, please ask a question on [StackOverflow](https://stackoverflow.com/questions/tagged/cleverhans).***

**Describe the bug**
It seems some of the tests for attacks include include unintentional bugs? To be specific, some targeted attacks sample targets as `np.random.randint(0, 1, n_samples)`. However, this function takes generates integers in `[lower_range, upper_range)` and thus, in this case, will always give 0. Is this intentional behaviour? (Example [here](https://github.com/tensorflow/cleverhans/blob/master/tests_tf/test_attacks.py#L959))

**Expected behavior**
Ideally the attack should work well in both scenarios, but using random samples may be a better test (instead of a model that would be biased towards one of the labels and pass some sub-tests?)

**Comment by jonasguan** [comment]
Hey @iamgroot42 , you have a very keen eye! This does look like a bug. However, we are discontinuing support for TF1, and will soon mark the current version of CleverHans as the final v3 release, before we update to v4. In an abundance of caution, I won't make the change since this is part of the test of the older TF1 code, lest I somehow break it right before release. However, if you notice this bug in the newer v4 code (changes upcoming!), please let us know in a new issue or PR. I know we haven't been active for a while, but we're back now :)
