### ISSUE TITLE
Cleverhans adversarial generation is extreamly slow

### ISSUE THREAD

**Issue by Jeevi10** [cleverhans-lab/cleverhans#1173]
if attack =="fsgm":
       fgsm = FastGradientMethod(DQNModel(model,env.action_space.n),model.sess)
       adv_x = fgsm.generate(obs_ph1, **fgsm_params)
       
adv_xin = model.sess.run(adv_x,{obs_ph: np.array(obs)[None]})*255.0

model= stable baseline DQN model.
DQNModel= cleverhans Model to create frop
obs_ph1,obs_ph = stable baseline placeholders. 
When use this to generate adversarial examples for RL. Its extremely slow. 
if I increase the epsilon value the generation become faster.
Can you please help with this issue?

**Comment by jonasguan** [comment]
Hey @Jeevi10 , FGSM isn't computationally intensive and shouldn't be very slow. Are you running on a GPU?

I'm going to close this issue for now since it's inactive for a while, and we're about to make some major updates. If you're still having similar problems, feel free to reopen an issue and mention this one.
