### ISSUE TITLE
Add a docstring linter to travis tests

### ISSUE THREAD

**Issue by goodfeli** [cleverhans-lab/cleverhans#366]
To make sure issues like https://github.com/tensorflow/cleverhans/issues/354 don't repeat, we could add a docstring linter to the travis tests.

There's one set up for Sphinx already in pylearn2.devtools. We already copied the PEP8 checker from that module so it shouldn't be too much work to also copy the docstring linter.

**Comment by yenchenlin** [comment]
Hello @goodfeli , I'm happy to help on this.

Just want to confirm, it seems like you also copied the docstring linter [here](https://github.com/tensorflow/cleverhans/blob/master/cleverhans/devtools/tests/docscrape.py#L775-L830).

Maybe we just need to remove the [temporarily disabled docstring test](https://github.com/tensorflow/cleverhans/blob/master/cleverhans/devtools/tests/test_format.py#L78-L79) and fix the files who violate the docstring rule?

Let me know if I got it wrong.

**Comment by goodfeli** [comment]
That would be great, thanks!

I'm not 100% sure I've copied everything needed by the disabled test, so there might be something more than just removing the linear that disables it.

**Comment by yenchenlin** [comment]
Got it.

By simply enabling the docstring test, I get the following output:
```
/Users/YenChen/Desktop/Python/cleverhans/cleverhans/attacks.py:
LBFGS class has no Parameters section
LBFGS:construct_graph:No Parameters section
LBFGS:generate_np:No Parameters section
LBFGS:get_or_guess_labels:Brief function summary is longer than 3 lines
LBFGS:get_or_guess_labels:No Parameters section
LBFGS:construct_variables:No Parameters section
LBFGS:generate:No Parameters section
LBFGS:parse_params:**missing** method-level docstring
...
/Users/YenChen/Desktop/Python/cleverhans/examples/multigpu_advtrain/utils_cifar.py:
...
__doc__:Line 2 exceeds 75 chars: "https://github.com/renmengye/r"...
__doc__:Line 8 exceeds 75 chars: "Permission is hereby granted, "...
__doc__:Line 9 exceeds 75 chars: "of this software and associate"...
__doc__:Line 10 exceeds 75 chars: "in the Software without restri"...
__doc__:Line 15 exceeds 75 chars: "The above copyright notice and"...
__doc__:Line 22 exceeds 75 chars: "LIABILITY, WHETHER IN AN ACTIO"...
__doc__:Line 23 exceeds 75 chars: "OUT OF OR IN CONNECTION WITH T"...
...
```

Since there are 400+ violations in total, I think we can 

1. Fix some of the important files (e.g., attack API)
2 Add the remaining of them (e.g., NIPS competition 2017) to whitelists and fix them later

May I know your opinion?

**Comment by npapernot** [comment]
Thanks for posting the result. I would be in favor of being more strict with the `cleverhans/` and `cleverhans_tutorials` folder than the `examples/` folder (and only have the linter on the first two folders). Note that right now we are already whitelisting the NIPS competition code from the pep8 checker that is running on all folders (main library in `cleverhans/`, tutorials in `cleverhans_tutorials/` and examples in `examples/`

**Comment by yenchenlin** [comment]
Thanks for the reply. I've used the tests to fix some files' docstring. However, I need your inputs on docstring format design.

Here's part of the outputs (but representative) after running docstring tests:
```
/Users/YenChen/Desktop/Python/cleverhans/cleverhans_tutorials/mnist_tutorial_jsma.py:
__doc__:**missing** module-level docstring
mnist_tutorial_jsma:No Parameters section
main:**missing** function-level docstring
```

It basically points out 3 problems:

1. We need module-level docstring for each file (tutorials part fixed in #367)
2. Current tests use keywords such as `Parameters` and `Returns` to detect docstring errors (see example [here](https://github.com/scikit-learn/scikit-learn/blob/34aad31924dc9c8551e6ff8edf4e729dbfc1b973/sklearn/linear_model/least_angle.py#L49-L50)). This format is adopted by both scikit-learn and pylearn2. 
Do we want to add these keywords to docstring or modify the tests to detect current format `:param xxx:`?
3. `main` function like [this](https://github.com/tensorflow/cleverhans/blob/master/cleverhans_tutorials/mnist_blackbox.py#L258) doesn't have docstring, do we need to add one to pass the test?

**Comment by npapernot** [comment]
1. thanks for the PR
2. I think it's fine to use the keywords, I checked TF and it also uses keywords rather than the structure we currently follow.
3. I would prefer to add an exception to the test not to check the main function because these are always empty and just calling the tutorial function (unless it's more complicated to add an exception than adding a simple docstring to the main function)

**Comment by jonasguan** [comment]
Closing since we're switching to Github Actions soon.
